"use client"

import "./page.css";
import { useEffect, useState } from "react";
import Link from "next/link";
import { API_BASE_URL, getApiUrl } from "@/config/api";

export default function Home() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);
  const [selectedReport, setSelectedReport] = useState(null);
  const [showpredictionlogin, setshowpredictionlogin] = useState(false);
  const [predictionLogic, setPredictionLogic] = useState("");

  async function fetchReports() {
    try {
      setLoading(true);
      const response = await fetch(getApiUrl(`/api/accident-reports?page=${page}&limit=${limit}`));
      const data = await response.json();
      setReports(data.data);
      setTotal(data.pagination.total);
      setLoading(false);
    } catch (error) {
      setLoading(false);
      console.error("Error fetching reports:", error);
    }
  }


  async function fetchNewReports() {
    try {
      setLoading(true);
      const response = await fetch(getApiUrl(`/api/sync-submitted-report`));
      const data = await response.json();
      if (data.success) {
        console.log("Successfully fetched new reports");
        setLoading(false);
        fetchReports();
      }

    } catch (error) {
      setLoading(false);
      console.error("Error fetching reports:", error);
    }
  }

  const handleClick = async (report_id) => {
    try {
      setLoading(true);
      const response = await fetch(getApiUrl(`/api/evaluate-report/${report_id}`), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      });
      setLoading(false);
      if (response.ok) {
        fetchReports();
      } else {
        console.error("Error predicting report:", response.statusText);
      }
    } catch (error) {
      setLoading(false);
      console.error("Error predicting report:", error);
    }
  };

  const handleRowClick = (report) => {
    setSelectedReport(report);
  };

  const closeModal = () => {
    setSelectedReport(null);
  };

  const showPredictionResult = (e, logic) => {
    e.stopPropagation();
    setPredictionLogic(logic || "No prediction logic available");
    setshowpredictionlogin(true);
  };

  const closePredictionModal = () => {
    setshowpredictionlogin(false);
    setPredictionLogic("");
  };

  useEffect(() => {
    fetchReports();
  }, [page]);

  return (
    <div className={"main"}>
      <div style={{ textAlign: "center", marginTop: "20px", marginBottom: "20px" }}>
        <h1 style={{marginBottom:"10px"}}>Accident Reports</h1>
        <p>
          Below is a list of accident reports with their prediction results
          and the logic behind the prediction. The prediction results are
          generated by a LLM model trained on historical data.
        </p>
      </div>
      <div className="action-buttons">
        <button onClick={fetchReports} style={{marginRight:"10px"}}>Refresh</button>
        <button onClick={fetchNewReports} style={{marginRight:"10px"}}>Fetch New Reports</button>
        <Link href="/criteria" className="criteria-link">
          <button>View Approval Criteria</button>
        </Link>
      </div>
      {loading && <p style={{ textAlign: "center" }}>Loading...</p>}
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Reported Date</th>
            <th>Approval Status</th>
            <th>Prediction Result</th>
            {/* <th>Logic Behind Prediction</th> */}
            <th>Predicted On</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {reports.map((report) => (
            <tr 
              key={report.report_id} 
              onClick={() => handleRowClick(report)} 
              style={{ cursor: "pointer" }}
              title={`Logic: ${report.logic_behind_prediction || 'No prediction logic available'}`}
            >
              <td>{report.report_id}</td>
              <td>{report.report_date ? new Date(report.report_date).toISOString().split('T')[0] : "N/A"}</td>
              <td>{report.approval_status}</td>
              <td>{report.prediction_result!=="Pending"?
                <button onClick={(e)=>{showPredictionResult(e,report.logic_behind_prediction)}}>{report.prediction_result}</button>
                :report.prediction_result}
                </td>
              {/* <td>{report.logic_behind_prediction}</td> */}
              <td>{report.predicted_on ? new Date(report.predicted_on).toISOString().split('T')[0] : "N/A"}</td>
              <td>
              <button onClick={(e) => { e.stopPropagation(); handleClick(report.report_id); }}>Predict</button>
            
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {loading && <p style={{ textAlign: "center" }}>Loading...</p>}
      <div className="pagination" style={{ textAlign: "center" }}>
        <button 
          onClick={() => setPage((prev) => Math.max(prev - 1, 1))} 
          disabled={page === 1}
        >
          Previous
        </button>
        <span>{(page - 1) * limit + reports.length}/{total}</span>
        <button 
          onClick={() => setPage((prev) => (prev * limit < total ? prev + 1 : prev))} 
          disabled={page * limit >= total}
        >
          Next
        </button>
      </div>
      
      {/* Prediction Logic Modal */}
      {showpredictionlogin && (
        <div className="modal" onClick={closePredictionModal}>
          <div className="modal-content prediction-modal" onClick={(e) => e.stopPropagation()}>
            <span className="close-button" onClick={closePredictionModal}>&times;</span>
            <h2>Prediction Logic</h2>
            <div className="logic-content">
              {predictionLogic.split('\n').map((paragraph, index) => (
                <p key={index}>
                  {paragraph.split(/\*\*(.*?)\*\*/).map((part, i) => {
                    // Handle bold text with **text** format
                    return i % 2 === 1 ? <strong key={i}>{part}</strong> : part;
                  })}
                </p>
              ))}
            </div>
            <button className="modal-button" onClick={closePredictionModal}>Close</button>
          </div>
        </div>
      )}
      
      {selectedReport && (
        <div className="modal" onClick={closeModal}>
          <div className="modal-content prediction-modal" onClick={(e) => e.stopPropagation()}>
            <h2>Report Details</h2>
            <pre>{JSON.stringify(selectedReport, null, 2)}</pre>
            <button className="modal-button" onClick={closeModal}>Close</button>
          </div>
        </div>
      )}
    </div>
  );
}
