"use client"

import "./page.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);
  const [selectedReport, setSelectedReport] = useState(null);

  async function fetchReports() {
    try {
      setLoading(true);
      const response = await fetch(`https://a590-202-181-7-69.ngrok-free.app/api/accident-reports?page=${page}&limit=${limit}`);
      const data = await response.json();
      setReports(data.data);
      setTotal(data.pagination.total);
      setLoading(false);
    } catch (error) {
      setLoading(false);
      console.error("Error fetching reports:", error);
    }
  }

  const handleClick = async (report_id) => {
    try {
      setLoading(true);
      const response = await fetch(`https://a590-202-181-7-69.ngrok-free.app/api/evaluate-report/${report_id}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      });
      setLoading(false);
      if (response.ok) {
        fetchReports();
      } else {
        console.error("Error predicting report:", response.statusText);
      }
    } catch (error) {
      setLoading(false);
      console.error("Error predicting report:", error);
    }
  };

  const handleRowClick = (report) => {
    setSelectedReport(report);
  };

  const closeModal = () => {
    setSelectedReport(null);
  };

  useEffect(() => {
    fetchReports();
  }, [page]);

  return (
    <div className={"main"}>
      <div>
        <h1>Accident Reports</h1>
        <p>
          Below is a list of accident reports with their prediction results
          and the logic behind the prediction. The prediction results are
          generated by a machine learning model trained on historical data.
        </p>
      </div>
      {loading && <p>Loading...</p>}
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Approval Status</th>
            <th>Prediction Result</th>
            <th>Logic Behind Prediction</th>
            <th>Predicted On</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {reports.map((report) => (
            <tr key={report.report_id} onClick={() => handleRowClick(report)}>
              <td>{report.report_id}</td>
              <td>{report.approval_status}</td>
              <td>{report.prediction_result}</td>
              <td>{report.logic_behind_prediction}</td>
              <td>{report.predicted_on || "N/A"}</td>
              <td>
                {report.approval_status === "Not Approved" ? (
                  <button onClick={(e) => { e.stopPropagation(); handleClick(report.report_id); }}>Predict</button>
                ) : (
                  <div>N/A</div>
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {loading && <p>Loading...</p>}
      <div className="pagination">
        <button 
          onClick={() => setPage((prev) => Math.max(prev - 1, 1))} 
          disabled={page === 1}
        >
          Previous
        </button>
        <span>{(page - 1) * limit + reports.length}/{total}</span>
        <button 
          onClick={() => setPage((prev) => (prev * limit < total ? prev + 1 : prev))} 
          disabled={page * limit >= total}
        >
          Next
        </button>
      </div>
      {selectedReport && (
        <div className="modal" onClick={closeModal}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h2>Report Details</h2>
            <pre>{JSON.stringify(selectedReport, null, 2)}</pre>
            <button onClick={closeModal}>Close</button>
          </div>
        </div>
      )}
    </div>
  );
}
