"use client"

import { useEffect, useState } from "react";
import Link from "next/link";
import { getApiUrl } from "../../config/api";
import "./reports.css";

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [total, setTotal] = useState(0);
  const [selectedReport, setSelectedReport] = useState(null);
  const [showpredictionlogin, setshowpredictionlogin] = useState(false);
  const [predictionLogic, setPredictionLogic] = useState("");
  // Add state for filters
  const [predictionFilter, setPredictionFilter] = useState("");
  const [approvalFilter, setApprovalFilter] = useState("");

  async function fetchReports() {
    try {
      setLoading(true);
      // Include filters in API request
      let url = getApiUrl(`/api/accident-reports?page=${page}&limit=${limit}`);
      
      // Add filters to the URL if they are set
      if (predictionFilter) {
        url += `&predictionResult=${predictionFilter}`;
      }
      if (approvalFilter) {
        url += `&status=${approvalFilter}`;
      }
      
      const response = await fetch(url);
      const data = await response.json();
      setReports(data.data);
      setTotal(data.pagination.total);
      setLoading(false);
    } catch (error) {
      setLoading(false);
      console.error("Error fetching reports:", error);
    }
  }
  
  // Function to reset filters
  const resetFilters = () => {
    setPredictionFilter("");
    setApprovalFilter("");
    setPage(1); // Reset to first page
  };

  async function fetchNewReports() {
    try {
      setLoading(true);
      const response = await fetch(getApiUrl(`/api/sync-submitted-report`));
      const data = await response.json();
      if (data.success) {
        console.log("Successfully fetched new reports");
        setLoading(false);
        fetchReports();
      }
    } catch (error) {
      setLoading(false);
      console.error("Error fetching reports:", error);
    }
  }

  const handleClick = async (report_id) => {
    try {
      setLoading(true);
      const response = await fetch(getApiUrl(`/api/evaluate-report/${report_id}`), {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      });
      setLoading(false);
      if (response.ok) {
        fetchReports();
      } else {
        console.error("Error predicting report:", response.statusText);
      }
    } catch (error) {
      setLoading(false);
      console.error("Error predicting report:", error);
    }
  };

  const handleRowClick = (report) => {
    setSelectedReport(report);
  };

  const closeModal = () => {
    setSelectedReport(null);
  };

  const showPredictionResult = (e, logic) => {
    e.stopPropagation();
    setPredictionLogic(logic || "No prediction logic available");
    setshowpredictionlogin(true);
  };

  const closePredictionModal = () => {
    setshowpredictionlogin(false);
    setPredictionLogic("");
  };

  useEffect(() => {
    fetchReports();
  }, [page, predictionFilter, approvalFilter]); // Add filters to dependency array

  return (
    <div className="reports-container">
      <header className="reports-header">
        <h1>Accident Reports</h1>
        <Link href="/dashboard">
          <button className="back-to-dashboard">Back to Dashboard</button>
        </Link>
      </header>
      
      <div className="reports-description">
        <p>
          Below is a list of accident reports with their prediction results
          and the logic behind the prediction. The prediction results are
          generated by a LLM model trained on historical data.
        </p>
      </div>
      
      <div className="action-buttons">
        <button onClick={fetchReports} className="action-button">Refresh</button>
        <button onClick={fetchNewReports} className="action-button">Fetch New Reports</button>
        <Link href="/criteria">
          <button className="action-button">View Approval Criteria</button>
        </Link>
      </div>
      
      {/* Add filter controls */}
      <div className="filters-container">
        <div className="filter-group">
          <label htmlFor="prediction-filter">Prediction Result:</label>
          <select 
            id="prediction-filter" 
            value={predictionFilter} 
            onChange={(e) => {
              setPredictionFilter(e.target.value);
              setPage(1); // Reset to first page when filter changes
            }}
          >
            <option value="">All Results</option>
            <option value="Pending">Pending</option>
            <option value="Approved">Approved</option>
            <option value="Disapproved">Disapproved</option>
          </select>
        </div>
        
        <div className="filter-group">
          <label htmlFor="approval-filter">Approval Status:</label>
          <select 
            id="approval-filter" 
            value={approvalFilter} 
            onChange={(e) => {
              setApprovalFilter(e.target.value);
              setPage(1); // Reset to first page when filter changes
            }}
          >
            <option value="">All Results</option>
            <option value="Pending">Pending</option>
            <option value="Approved">Approved</option>
            <option value="Disapproved">Disapproved</option>
          </select>
        </div>
        
        <button 
          onClick={resetFilters} 
          className="reset-filters-button"
          disabled={!predictionFilter && !approvalFilter}
        >
          Reset Filters
        </button>
      </div>
      
      {loading && <p className="loading-indicator">Loading...</p>}
      
      {/* Show a message when no results are found */}
      {!loading && reports.length === 0 && (
        <div className="no-results">
          <p>No reports found with the selected filters.</p>
        </div>
      )}
      
      {reports.length > 0 && (
        <table className="reports-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Reported Date</th>
              <th>Approval Status</th>
              <th>Prediction Result</th>
              <th>Predicted On</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr 
                key={report.report_id} 
                onClick={() => handleRowClick(report)} 
                style={{ cursor: "pointer" }}
                title={`Logic: ${report.logic_behind_prediction || 'No prediction logic available'}`}
              >
                <td>{report.report_id}</td>
                <td>{report.report_date ? new Date(report.report_date).toISOString().split('T')[0] : "N/A"}</td>
                <td>{report.approval_status}</td>
                <td>
                  {report.prediction_result !== "Pending" ? (
                    <button onClick={(e) => showPredictionResult(e, report.logic_behind_prediction)}>
                      {report.prediction_result}
                    </button>
                  ) : report.prediction_result}
                </td>
                <td>{report.predicted_on ? new Date(report.predicted_on).toISOString().split('T')[0] : "N/A"}</td>
                <td>
                  <button 
                    onClick={(e) => { e.stopPropagation(); handleClick(report.report_id); }}
                    className="predict-button"
                  >
                    Predict
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      
      <div className="pagination">
        <button 
          onClick={() => setPage((prev) => Math.max(prev - 1, 1))} 
          disabled={page === 1}
          className="pagination-button"
        >
          Previous
        </button>
        <span className="pagination-info">{(page - 1) * limit + reports.length}/{total}</span>
        <button 
          onClick={() => setPage((prev) => (prev * limit < total ? prev + 1 : prev))} 
          disabled={page * limit >= total}
          className="pagination-button"
        >
          Next
        </button>
      </div>
      
      {/* Prediction Logic Modal */}
      {showpredictionlogin && (
        <div className="modal" onClick={closePredictionModal}>
          <div className="modal-content prediction-modal" onClick={(e) => e.stopPropagation()}>
            <span className="close-button" onClick={closePredictionModal}>&times;</span>
            <h2>Prediction Logic</h2>
            <div className="logic-content">
              {predictionLogic.split('\n').map((paragraph, index) => (
                <p key={index}>
                  {paragraph.split(/\*\*(.*?)\*\*/).map((part, i) => {
                    // Handle bold text with **text** format
                    return i % 2 === 1 ? <strong key={i}>{part}</strong> : part;
                  })}
                </p>
              ))}
            </div>
            <button className="modal-button" onClick={closePredictionModal}>Close</button>
          </div>
        </div>
      )}
      
      {selectedReport && (
        <div className="modal" onClick={closeModal}>
          <div className="modal-content prediction-modal" onClick={(e) => e.stopPropagation()}>
            <h2>Report Details</h2>
            <pre>{JSON.stringify(selectedReport, null, 2)}</pre>
            <button className="modal-button" onClick={closeModal}>Close</button>
          </div>
        </div>
      )}
    </div>
  );
}
